apiVersion: networking.k8s.io/v1
kind: 'Ingress'
metadata:
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.nav.no/arbeidsgiver/sykmeldte
  labels:
    app: dinesykmeldte
    team: teamsykmelding
  name: sykefravaerarbeidsgiver-redirect
  namespace: teamsykmelding
spec:
  ingressClassName: gw-nav-no
  rules:
    - host: www.nav.no
      http:
        paths:
          - backend:
              service:
                name: dinesykmeldte
                port:
                  number: 80
            path: /sykefravaerarbeidsgiver(/.*)?
            pathType: ImplementationSpecific
